In [2]:
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.decomposition import PCA
import math
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
import xgboost as xgb
from sklearn.externals import joblib
import warnings
import tushare as ts
warnings.filterwarnings("ignore")

In [2]:
pro = ts.pro_api('52119551ebc32c734a42fd61ccf33344fde3c6195b0aacec58d15140')

In [25]:
colums=['801010.SI', '801020.SI', '801030.SI','801040.SI', '801050.SI', '801080.SI', '801110.SI', '801120.SI',
        '801130.SI', '801140.SI', '801150.SI', '801160.SI', '801170.SI', '801180.SI', '801200.SI', '801210.SI',
        '801230.SI', '801250.SI', '801260.SI', '801270.SI', '801280.SI', '801300.SI', '801710.SI', '801720.SI',
        '801730.SI', '801740.SI', '801750.SI', '801760.SI', '801770.SI', '801780.SI', '801790.SI', '801880.SI',
        '801890.SI', '802600.SI']
df_pr = pd.DataFrame()
df = pd.DataFrame()
for arr in colums:
    df1=pro.sw_daily(ts_code=arr, start_date='20190521', end_date='20190625')
    df1=df1.sort_values(by="trade_date",ascending= True)
    df = pd.concat([df, df1])
# regressor=joblib.load('./lstm4.model')
# df=pro.sw_daily(ts_code='801880.SI', start_date='20190521', end_date='20190625')
df.loc[df['pct_change']>0,'y']=1
df.loc[df['pct_change']<0,'y']=0
df['vol_change'] = df['vol'].pct_change()
df['low_change'] = df['low'].pct_change()
df['high_change'] = df['high'].pct_change()
df['gaodi'] = (df['high'] - df['low']) / df['low']
df['gaoclo'] = (df['high'] - df['close']
                  ) / (df['high'] - df['low'])
df['diclo'] = (df['close'] - df['low']) / (df['high'] - df['low'])
df['pct_change'] = df['pct_change'] / 10
df = df[['ts_code', 'trade_date', 'name', 'pct_change',
                 'vol_change', 'high_change', 'low_change', 'gaodi', 'gaoclo', 'diclo', 'y']]
# df=df.tail(n=15)
# dataset = df.values
# x = dataset[0:15, 3:11].tolist()
# x = np.array(x)
# x = np.reshape(x, (1, x.shape[0], x.shape[1]))
# ytest = regressor.predict(x)
# ytest

array([[0.51383907, 0.0794052 , 0.78035617]], dtype=float32)

In [39]:
regressor1=joblib.load('./model/1lstm4.model')
regressor2=joblib.load('./model/2lstm4.model')
regressor3=joblib.load('./model/3lstm4.model')
df_pr = pd.DataFrame()
colums1=['801160.SI','801790.SI','801880.SI']
for arr2 in colums1:
    df=pro.sw_daily(ts_code=arr2, start_date='20190521', end_date='20190625')
    df.loc[df['pct_change']>0,'y']=1
    df.loc[df['pct_change']<0,'y']=0
    df['vol_change'] = df['vol'].pct_change()
    df['low_change'] = df['low'].pct_change()
    df['high_change'] = df['high'].pct_change()
    df['gaodi'] = (df['high'] - df['low']) / df['low']
    df['gaoclo'] = (df['high'] - df['close']
                      ) / (df['high'] - df['low'])
    df['diclo'] = (df['close'] - df['low']) / (df['high'] - df['low'])
    df['pct_change'] = df['pct_change'] / 10
    df = df[['ts_code', 'trade_date', 'name', 'pct_change',
                     'vol_change', 'high_change', 'low_change', 'gaodi', 'gaoclo', 'diclo', 'y']]
    df1=df.tail(n=15)
    dataset = df1.values
    x2 = dataset[0:15, 3:11].tolist()
    x2 = np.array(x2)
    x2 = np.reshape(x2, (1, x2.shape[0], x2.shape[1]))
    y_p =  pd.DataFrame()
    ytest1 =  pd.DataFrame(regressor1.predict(x2))
    ytest2 =  pd.DataFrame(regressor2.predict(x2))
    ytest3 =  pd.DataFrame(regressor3.predict(x2))
    y_p = pd.concat([ytest1, ytest2])
    y_p = pd.concat([y_p, ytest3])
    y_p['ts_code'] = arr2
    y_p['trade_date'] = [20190701, 20190702, 20190703]
    df_pr = pd.concat([df_pr, y_p])
df_pr.columns = ['p', 'ts_code', 'trade_date']
df_pr= df_pr[['ts_code', 'trade_date', 'p']]
df_pr

     ts_code  trade_date         p
0  801160.SI    20190701  0.188480
0  801160.SI    20190702  0.000737
0  801160.SI    20190703  0.954984
0  801790.SI    20190701  0.905897
0  801790.SI    20190702  0.369505
0  801790.SI    20190703  0.464786
0  801880.SI    20190701  0.835080
0  801880.SI    20190702  0.136465
0  801880.SI    20190703  0.995026

In [ ]:
df_pr=df_pr+y

In [11]:
regressor1=joblib.load('./1lstm0.model')
regressor2=joblib.load('./2lstm0.model')
regressor3=joblib.load('./3lstm0.model')
df_pr = pd.DataFrame()
for arr1 in colums:
    df2=df.loc[df['ts_code']==arr1]
    df2=df2.tail(n=15)
    dataset = df2.values
    x1 = dataset[0:15, 3:11].tolist()
    x1 = np.array(x1)
    x1 = np.reshape(x1, (1, x1.shape[0], x1.shape[1]))
    y_p =  pd.DataFrame()
    ytest1 = regressor1.predict(x1)
    ytest2 = regressor2.predict(x1)
    ytest3 = regressor3.predict(x1)
    y_p= pd.DataFrame([ytest1,ytest2,ytest2])
    y_p = y_p.T
    y_p['ts_code'] = arr1
    y_p['trade_date'] = [20190628, 20190701, 20190702]
    df_pr = pd.concat([df_pr, y_p])
df_pr.columns = ['p', 'ts_code', 'trade_date']
df_pr = df_pr[['ts_code', 'trade_date', 'p']]
df_pr.to_csv('./结果1')

In [12]:
df_jieguo1=pd.read_csv('./结果1')
df_jieguo2=pd.read_csv('./结果2')
df_jieguo3=pd.read_csv('./结果3')
df_jieguo4=pd.read_csv('./结果4')
df_jieguo5=pd.read_csv('./结果5')

In [13]:
jieguo=pd.DataFrame()
jieguo['ts_code']=df_jieguo1['ts_code']
for i in range(len(jieguo)):
    jieguo['ts_code'][i]= jieguo['ts_code'][i][0:6]
jieguo['ts_code']=jieguo['ts_code'].astype('int')
jieguo['trade_date']=df_jieguo1['trade_date']
jieguo['p']=(df_jieguo1['p']+df_jieguo2['p']+df_jieguo3['p']+df_jieguo4['p']+df_jieguo5['p'])/5

In [14]:
jieguo.to_csv('./Submision.csv')

In [15]:
jieguo

     ts_code  trade_date         p
0     801010    20190626  0.731844
1     801010    20190627  0.262117
2     801010    20190628  0.632171
3     801020    20190626  0.428690
4     801020    20190627  0.174628
5     801020    20190628  0.741567
6     801030    20190626  0.256401
7     801030    20190627  0.352556
8     801030    20190628  0.768952
9     801040    20190626  0.820048
10    801040    20190627  0.428580
11    801040    20190628  0.357217
12    801050    20190626  0.894917
13    801050    20190627  0.050705
14    801050    20190628  0.265285
15    801080    20190626  0.523911
16    801080    20190627  0.298193
17    801080    20190628  0.726387
18    801110    20190626  0.362232
19    801110    20190627  0.370253
20    801110    20190628  0.795477
21    801120    20190626  0.745243
22    801120    20190627  0.014934
23    801120    20190628  0.615265
24    801130    20190626  0.649846
25    801130    20190627  0.028869
26    801130    20190628  0.739168
27    801140    20190626  0.484318
28    801140    20190627  0.170810
29    801140    20190628  0.630150
..       ...         ...       ...
72    801730    20190626  0.548113
73    801730    20190627  0.271821
74    801730    20190628  0.714164
75    801740    20190626  0.619174
76    801740    20190627  0.393439
77    801740    20190628  0.685842
78    801750    20190626  0.678538
79    801750    20190627  0.185249
80    801750    20190628  0.505857
81    801760    20190626  0.575739
82    801760    20190627  0.466238
83    801760    20190628  0.685005
84    801770    20190626  0.253751
85    801770    20190627  0.224803
86    801770    20190628  0.798919
87    801780    20190626  0.194953
88    801780    20190627  0.734886
89    801780    20190628  0.565280
90    801790    20190626  0.342085
91    801790    20190627  0.722816
92    801790    20190628  0.531723
93    801880    20190626       NaN
94    801880    20190627       NaN
95    801880    20190628       NaN
96    801890    20190626  0.678195
97    801890    20190627  0.207431
98    801890    20190628  0.595100
99    802600    20190626  0.542041
100   802600    20190627  0.090039
101   802600    20190628  0.768280

[102 rows x 3 columns]

In [4]:
y= pd.DataFrame(1,2,3)
y

TypeError: object of type 'int' has no len()